Repository abhilashmnair/HacktoberFest2021, pull requests merged in 2021-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted

#3 Add files via upload
  images/img.jfif
Labels: hacktoberfest-accepted

#4 Create CPP
  CPP
Labels: hacktoberfest-accepted

#6 Create Octopus.cpp
  C++/Octopus.cpp
Labels: hacktoberfest-accepted

#7 kruskals algorithm in cpp
  C++/kruskals.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#11 Created base conversion program in cpp
  C++/baseConversion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#10 Created perfection.cpp
  C++/perfection.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#9 Created Essential Java Programs for Repo
  Java/Anagram.java
  Java/LeftRotateArrayElement.java
  Java/RemoveDuplicate.java
  Java/RightRotate.java
  Java/SumRomColoumn.java
Labels: hacktoberfest, hacktoberfest-accepted

#12 Added Python Folder
  Python/placeholder
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 amstrongnumber.cpp
  amstrongnumber.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#14 Update primeNumbers.cpp
  C++/primeNumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 Created Blackjack in Python
  Python/blackjack.py
Labels: hacktoberfest, hacktoberfest-accepted

#18 Create dfs.cpp
  C++/dfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 Create bellmanford.cpp
  C++/bellmanford.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create topological_sort.cpp
  C++/topological_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create directed_cycle.cpp
  C++/directed_cycle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 add bubble sort in c++
  C++/bubblesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#22 palindrone.cpp
  palindrone.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#23 Create medianof2sortedarrays.cpp
  C++/medianof2sortedarrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added implementation of avl tree
  C++/avlTree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#25 Create djikstras.cpp
  djikstras.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#26 Created Easter Determination Algorithm (Java)
  Java/Easter_Algorithm.java
Labels: hacktoberfest, hacktoberfest-accepted

#27 linked list program by Amit giri ( Amitlpu-840 )
  C++/linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#28 Snake Game in C
  C/Snake_Game.c
Labels: hacktoberfest, hacktoberfest-accepted

#29 SIEVE OF ERATOSTHENES
  C++/SIEVE.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 Binary search
  C++/BINARY SEARCH.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#31 added a c++ prog to add a node in a specific position in a linked list
  C++/Insert a node in a specific position in a linked list.cpp
  C++/print linkedlist in reverse.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 BubbleSort program Added using Java.
  Java/Bubblesort.java
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added Quicksort in Java
  Java/quicksort.java
Labels: hacktoberfest, hacktoberfest-accepted

#36 Adding Binary Search to JAVA.
  Java/BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#37 Tower of Hanoi
  C++/Tower Of Hanoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 Create trie.cpp
  C++/trie.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#39 HeapSort program Added using Java.
  Java/Heapsort.java
Labels: hacktoberfest, hacktoberfest-accepted

#40 Reversing Linked List using three sliding pointer method
  C/Linked List/Reversing Linked List using three sliding pointer method.c
Labels: hacktoberfest, hacktoberfest-accepted

#41 Merge sort
  C++/merge sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 Added InsertionSort program using Java.
  Java/Insertionsort.java
Labels: hacktoberfest, hacktoberfest-accepted

#43 creat race.cpp
  C++/race.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added GCD in C++
  C++/GCD.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added Golang Language folder
  Golang/placeholder
Labels: hacktoberfest, hacktoberfest-accepted

#47 Added Dart Language Folder
  Dart/placeholder
Labels: hacktoberfest, hacktoberfest-accepted

#45 MergeSort program added using Java .
  Java/Mergesort.java
Labels: hacktoberfest, hacktoberfest-accepted

#48 SelectionSort program added using Java.
  Java/Selectionsort.java
Labels: hacktoberfest, hacktoberfest-accepted

#49 Added JavaScript Language folder
  Javascript/placeholder
Labels: hacktoberfest, hacktoberfest-accepted

#50 Added GCD in C++
  C++/Added GCD in C++
Labels: hacktoberfest, hacktoberfest-accepted

#51 Revert "Added GCD in C++"
  C++/Added GCD in C++
Labels: hacktoberfest, hacktoberfest-accepted

#55 Added BinaryTree_RightSideView.cpp
  C++/BinaryTree_RightSideView.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#54 Add heapsort and fizzbuzz in python
  Python/fizzbuzz.py
  Python/heapsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 Added Kadane Algorithm C++
  C++/kadaneAlgorithm
  C++/kadaneAlgorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#58 Snake Game
  C++/snakegame.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#59 BFS Traversal Of a Graph Using Queue
  C++/bfsTraversalOfGraph.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#60 Check linked list is palindrome or not
  Python/palindrome_linked_list.py
Labels: hacktoberfest, hacktoberfest-accepted

#62 stop inspacting the website
  Javascript/inspactor.js
Labels: hacktoberfest, hacktoberfest-accepted

#53 Added Binary_tree_is_symmetirc_or_not.cpp
  C++/Binary_tree_is_symmetirc_or_not.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 Frequency a numbers in array
  C/Frequency_off_number.c
Labels: hacktoberfest, hacktoberfest-accepted

#64 AVL Tree Insertion and Deletion
  C++/AVLtreeInsertionAndDeletion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create a fibonacci sequence using python
  Python/fibonacci.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#73 Added the game - ChopSticks to the python folder
  Python/Chopsticks.py
Labels: hacktoberfest, hacktoberfest-accepted

#72 Added KMP Algorithm
  C++/kmpalgorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#67 Total number of binary search trees possible with n keys
  C++/possibleBinarySearchTrees.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#69 Trie Insertion and search
  Java/CircularLinkedList.java
  Java/trieInsertSearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#70 Create matrix_multiplication.cpp
  C++/matrix_multiplication.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 Create a Pyramid Pattern using Java.
  Java/Pattern.java
Labels: hacktoberfest, hacktoberfest-accepted

#74 add fizzbuzz in golang
  Golang/fizzbuzz.go
Labels: hacktoberfest, hacktoberfest-accepted

#75 Added Queue Code
  C++/queue_pragya644.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#76 Sum of N Fibonacci numbers DP
  C#/SumOfNFibonacciNumbersDP.cs
Labels: hacktoberfest, hacktoberfest-accepted

#79 mergesort entered
  C++/mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#80 Revert "mergesort entered"
  C++/mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#81 DOUBLY LINKED LIST
  Java/DoublyLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#82 Coin Change Permutations and String Permutations
  Java/CoinChangePermutation.java
  Java/PrintPermutations.java
Labels: hacktoberfest, hacktoberfest-accepted

#85 Add website-blocker.py
  Python/website-blocker.py
Labels: hacktoberfest, hacktoberfest-accepted

#91 Adding a Simple Binary Search program in Python
  Python/BinarySearch.py
Labels: hacktoberfest, hacktoberfest-accepted

#88 Create Hanoi Tower.cpp
  C++/Pyramid.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#92 Added queue using two stacks
  C++/Queue_using_two_stacks.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#90 Create String concatenation.py
  Python/String concatenation.py
Labels: hacktoberfest, hacktoberfest-accepted

#93 Pull request
  C/C_Program_without_main()_function.c
Labels: hacktoberfest, hacktoberfest-accepted

#94 pr
  C/Number_in_Characters.c
  Number_in_Characters.c
Labels: hacktoberfest, hacktoberfest-accepted

#95 Leetcode Problem solved.
  Javascript/leetcodeprob.js
Labels: hacktoberfest, hacktoberfest-accepted

#96 Stock span Problem
  Java/Maxofmin.java
  Java/RectArea.java
  Java/Stockspan.java
Labels: hacktoberfest, hacktoberfest-accepted

#97 Add Linear Search algorithm in Javascript
  Javascript/linearSearch.js
Labels: hacktoberfest, hacktoberfest-accepted

#98 Added Program to implement Stack using two queue
  C++/stackUsingTwoQueue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#100 Added Depth First Search Algorithm
  Java/DFS.java
Labels: hacktoberfest, hacktoberfest-accepted

#99 Solution to the codechef problem ceiling sum
  C++/Ceiling Sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#102 Added Binary Search Tree Implementation with Traversal
  Java/BST.java
Labels: hacktoberfest, hacktoberfest-accepted

#104 Created Stack Program in C
  C/Stack.c
Labels: hacktoberfest, hacktoberfest-accepted

#105 Added python code for Insertion sort
  Python/insertion_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#107 Added code to check leap year in python
  Python/check_leap_year.py
Labels: hacktoberfest, hacktoberfest-accepted

#109 add fibonacci series in golang
  Golang/fibonacci.go
Labels: hacktoberfest, hacktoberfest-accepted

#110 Created merge sort
  Python/Merge_Sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#112 This python code shows live time.
  Python/time.py
Labels: hacktoberfest, hacktoberfest-accepted

#114 Create Strassen_matrix.cpp
  C++/Strassen_matrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#115 Create MatrixMultiplication.cpp
  C++/MatrixMultiplication.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 Fibonacci Series and Binary Search Program
  C++/Fibonacci Series.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#116 N Queen problem
  C++/n_queen.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#117 Create Zigzag_pattern.cpp
  C++/Zigzag_pattern.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#118 Implemented simple mechanical energy calculation script in C#
  C#/ConsoleMechanicalEnergyCalculator.cs
Labels: hacktoberfest, hacktoberfest-accepted

#119 Create Reverse_of_2DMatrix.py
  Python/Reverse_of_2DMatrix.py
Labels: hacktoberfest, hacktoberfest-accepted

#120 Create Check_ArmstrongNo.py
  Python/Check_ArmstrongNo.py
Labels: hacktoberfest, hacktoberfest-accepted

#121 Reverse Number is added
  C++/ReverseNumber.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#122 RSA_cryptography_algorithm Added
  C++/RSA_cryptography_algorithm.cpp
  C++/intersection_point_Of_two_linkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#123 Added a while loop that counts down bottles of beer
  Javascript/bottlesOfBeer.js
Labels: hacktoberfest, hacktoberfest-accepted

#125 Create Bellmanford.cpp
  C++/Bellmanford.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#103 Added Doubly Linked List with all operations
  Java/DoublyLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#126 (c++) added linked list solutions
  C++/Clone LinkedList With Next And Random Pointer.cpp
  C++/Flatten binary tree to linked list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#127 Create insertion sort.cpp
  C++/insertion sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#128 Added sum_of_all_subarray.cpp
  C++/sum_of_all_subarray.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#129 Added Current Weather Display App in python
  C/maze_game.c
  Python/CurrentWeatherDisplayApp.py
Labels: hacktoberfest, hacktoberfest-accepted

#130 Some Codechef Questions added
  C++/Competitive Programming/Codechef/LongChallenge/ques1_SEP.cpp
  C++/Competitive Programming/Codechef/LongChallenge/ques1_SEP.exe
  C++/Competitive Programming/Codechef/LongChallenge/ques2_SEP.cpp
  C++/Competitive Programming/Codechef/LongChallenge/ques2_SEP.exe
  C++/Competitive Programming/Codechef/LongChallenge/ques3_SEP.cpp
  C++/Competitive Programming/Codechef/LongChallenge/ques3_SEP.exe
  C++/Competitive Programming/Codechef/Starters/c.cpp
  C++/Competitive Programming/Codechef/Starters/ques1_SEP.cpp
  C++/Competitive Programming/Codechef/Starters/ques1_SEP.exe
  C++/Competitive Programming/Codechef/Starters/ques2_SEP.cpp
  C++/Competitive Programming/Codechef/Starters/ques2_SEP.exe
  C++/Competitive Programming/Codechef/Starters/ques3_SEP.cpp
  C++/Competitive Programming/Codechef/Starters/ques3_SEP.exe
  C++/Competitive Programming/Cookoff/ques1_SEP.cpp
  C++/Competitive Programming/Cookoff/ques1_SEP.exe
  C++/Competitive Programming/Cookoff/ques2_SEP.cpp
  C++/Competitive Programming/Cookoff/ques2_SEP.exe
  C++/Competitive Programming/Cookoff/ques3_SEP.cpp
  C++/Competitive Programming/Cookoff/ques3_SEP.exe
Labels: hacktoberfest, hacktoberfest-accepted

#131 Added binary search in a list
  Python/binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted

#132 added insertion sort.c
  C/insertionsort.c
Labels: hacktoberfest, hacktoberfest-accepted

#133 all_soln_n_queen_BITMASKING-optiimized.cpp
  C++/all_soln_n_queen_BITMASKING-optiimized.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#134 Added a program to concatenate of two singly linked list
  C/single_linklist_concatenation.c
Labels: hacktoberfest, hacktoberfest-accepted

#136 added code to check and count vowels and consonants in a string using python
  Python/count_vowels_consonant.py
Labels: hacktoberfest, hacktoberfest-accepted

#137 Create degree_to_radian.cpp
  C++/degree_to_radian.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#138 added code for python program to reverse a given string
  Python/reverse_string_using_loops.py
Labels: hacktoberfest, hacktoberfest-accepted

#140 Loop detector in linked list program
  C++/loop_detector_in_linkedlist
Labels: hacktoberfest, hacktoberfest-accepted

#142 Add QRCode_Maker to Python
  Python/QRCode_Maker.py
Labels: hacktoberfest, hacktoberfest-accepted

#141 Added Important question in java
  Java/MergeIntervals.java
Labels: hacktoberfest, hacktoberfest-accepted

#143 I m not using ctr variable and cmath in my code.
  C++/primeNumbers.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#145 Delete placeholder
  C++/placeholder
Labels: hacktoberfest, hacktoberfest-accepted

#146 Added TowerofHanoi in Java
  Java/TowerofHanoi.java
Labels: hacktoberfest, hacktoberfest-accepted

#149 Update Readme.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#161 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#154 Password.py
  Python/Password.py
Labels: hacktoberfest, hacktoberfest-accepted

#155 Create reverse_number.cpp
  C++/reverse_number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#156 Added Extended Euclidean Algorithm Python File
  Python/extended_euclidean_algorithm.py
Labels: hacktoberfest, hacktoberfest-accepted

#157 Added some CP problems and algorithms
  .DS_Store
  C++/ Median Maximization.cpp
  C++/ Seating Arrangements.cpp
  C++/ Slay the Dragon.cpp
  C++/CQXYM Count Permutations.cpp
  C++/Diameter of Graph.cpp
  C++/MIN-MEX Cut.cpp
  Python/BT - 1.ipynb
  Python/BT-2.ipynb
  Python/Combinatorics Homework.py
  Python/Complete OOPS.ipynb
  Python/Linked List.ipynb
  Python/Queue - all algo.ipynb
  Python/Regular Bracket Sequences.py
  Python/Search Sort Recurision.ipynb
  Python/Stack.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#159 Tranverse Matrix.
  C++/Transverse Matrix
Labels: hacktoberfest, hacktoberfest-accepted

#162 Create odious.java
  Java/odious.java
Labels: hacktoberfest, hacktoberfest-accepted

#164 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#158 Simple and Scientific Calculator.
  C++/Simple and Scientific Calculator
Labels: hacktoberfest, hacktoberfest-accepted

#163 Matrix printing in spiral order in C++
  C++/Print_matrix_ in _spiral_order.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#165 Added 2 new questions.
  C++/Longest_Inc_subsequence_using_BinarySearch.cpp
  C++/Standard_Edit_Distance.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#168 Student_Class.cpp
  C++/Student_Class.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#169 Armstrong_no.cpp
  C++/Armstrong_no.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#170 factorial.cpp
  C++/factorial.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#172 Implemented simple kinetic energy calculation script in C#
  C#/ConsoleKineticEnergyCalculator.cs
Labels: hacktoberfest, hacktoberfest-accepted

#173 structure.cpp
  structure.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#174 Create burst-balloons-leetcode312.cpp
  C++/burst-balloons-leetcode312.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#176 Calculator (Menu Driven) Program
  C/Calculator (Menu Driven) Program.c
Labels: hacktoberfest, hacktoberfest-accepted

#177 maze problem
  C++/maze.cpp
  C/Implementing_reverse_elements_in_queue.c
Labels: hacktoberfest, hacktoberfest-accepted

#179 Rock papaer scissors game
  C++/Rock paper Scissors game
Labels: hacktoberfest, hacktoberfest-accepted

#181 Create reverse array
  C++/reverse array
Labels: hacktoberfest, hacktoberfest-accepted

#183 Added Linear Regression
  Machine Learning/LinearRegression.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#184 added code to calculate amount after discount
  Python/discount.py
Labels: hacktoberfest, hacktoberfest-accepted

#187 Quick_Sort
  C++/Quick_Sort
Labels: hacktoberfest, hacktoberfest-accepted

#188 leap year
  C++/Leap year
Labels: hacktoberfest, hacktoberfest-accepted

#190 Added rotate_an_array.cpp
  C++/Rotate_an_array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#191 Transpose of matrix
  Python/Transpose of matrix.py
Labels: hacktoberfest, hacktoberfest-accepted

#192 Python code for bubble sort
  Python/bubble_sort.py
Labels: hacktoberfest, hacktoberfest-accepted
